### ISSUE TITLE
Not all sites has description.

### ISSUE THREAD

**Issue by janisz** [javers/javers.github.io#89]
Currently only one page (index) has description. This disables Twitter cards functionality because descriptions are required. Please provide description for all pages.

<details>
https://javers.org/support

```
INFO:  Page fetched successfully
INFO:  12 metatags were found
INFO:  twitter:card = summary tag found
ERROR: Required meta tag missing (twitter:text:description)
```
</details>

**Comment by bartoszwalacik** [comment]
added, as a copy of title tag :p

**Comment by janisz** [comment]
I left a comment on the commit https://github.com/javers/javers.github.io/commit/105b73a8e3166d9d45eb492450fadcc55412dd46#commitcomment-22752981

**Comment by bartoszwalacik** [comment]
okay, now:

```
<meta name="description" content="{% if page.description %}{{ page.description }}{% else %}{{ site.description }}{% endif %}">
```
